### ISSUE TITLE
Allow file uploads instead of pasting

### ISSUE THREAD

**Issue by dfederm** [dfederm/ClickerHeroesTracker#160]
See: https://stackoverflow.com/a/40216616/7065632

**Comment by koutoftimer** [comment]
IMHO, something like this should work

```
<input type="file" onchange="fillSaveDataTextarea()" />

fillSaveDataTextarea = (e) => { 
  let fr = new FileReader(); 
  fr.onload = (e) => textarea.value = e.target.result; 
  fr.readAsText(e.target.files[0])
}
```
(not sure about `textarea.value`, because of angular's data binding, but I have modified doom in this way via dev tools and it works. But I have emmited onchange event manually by adding and removing a space in the textarea...)

I mean, no additional data handling required on the server side, just single input and function to read savefile and fill `textarea`. Solutions that you can see in provided post require such handling.

Looks like lifehack, but it is a stupidly easy solution if you like KISS.

**Comment by dfederm** [comment]
@koutoftimer yes, look at the link in the issue description. It uses something similar to what you have,

**Comment by koutoftimer** [comment]
Just want to point files that require changes: 
- https://github.com/dfederm/ClickerHeroesTracker/blob/master/WebClient/src/components/uploadDialog/uploadDialog.html#L15
- https://github.com/dfederm/ClickerHeroesTracker/blob/master/WebClient/src/components/uploadDialog/uploadDialog.ts#L73

**Comment by koutoftimer** [comment]
@dfederm I found that when press "Save" button, savefile is going to the clipboard and you don't have to even save it.

**Comment by dfederm** [comment]
@koutoftimer I'm not sure what you're getting at. I think it's common knowledge that it puts the same file in your clipboard.
